name = "statusphere"
main = "build/worker/shim.mjs"
compatibility_date = "2025-04-08"

[build]
command = "cargo install -q worker-build && worker-build --release"

# database for status records
[[d1_databases]]
binding = "DB"
database_name = "statusphere-statuses"
database_id = "8dd5dea9-b626-48d5-8639-3045ef823a41"


# simple kv store for auth state/session mappings
[[kv_namespaces]]
binding = "KV"
id = "511f1dc7efdf4eba8c0df504c3864b04"


# log requests using worker logs
[observability.logs]
enabled = true
invocation_logs = false

[vars]
# for use in oauth redirect links & etc
HOST = "https://statusphere-w.inanna-c38.workers.dev"

# serves css without having to spin up a worker
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"



# used for live updates via websocket
[durable_objects]
bindings = [
  { name = "MSGBROKER", class_name = "MsgBroker" },
  { name = "LISTENER", class_name = "JetstreamListener" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["MsgBroker", "JetstreamListener"]